image: alpine:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd ~/crypto-bot-dev/front-admin
    - git fetch && git pull
    - npm i
    - npm run build
    - rm -rf ../admin-front-server/static
    - cp -R build/ ../admin-front-server/static
  only:
    - master
